// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCompra.Persistence;

namespace SistemaCompra.Persistence.Migrations
{
    [DbContext(typeof(GoodPlaceContext))]
    partial class GoodPlaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SistemaCompra.Domain.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("FornecedorGanhadorId")
                        .HasColumnType("int");

                    b.Property<double>("Frete")
                        .HasColumnType("double");

                    b.Property<int>("FrmPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrazoCotacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PrazoOferta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.Property<int>("fornecedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fornecedorId");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("SistemaCompra.Domain.FamiliaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("FamiliaProdutos");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Endereco")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FamiliaProdId")
                        .HasColumnType("int");

                    b.Property<int?>("FamiliaProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("IdFamiliaProduto")
                        .HasColumnType("int");

                    b.Property<int>("InscricaoEstadual")
                        .HasColumnType("int");

                    b.Property<int>("InscricaoMunicipal")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoRanking")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaProdutoId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("SistemaCompra.Domain.ItemCotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCotacao")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitacaoProduto")
                        .HasColumnType("int");

                    b.Property<double>("PrecoUnit")
                        .HasColumnType("double");

                    b.Property<int>("QtdeProduto")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitacaoProdutoProdutoid")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitacaoProdutoSolicitacaoid")
                        .HasColumnType("int");

                    b.Property<int>("cotacaoId")
                        .HasColumnType("int");

                    b.Property<int>("itemPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cotacaoId");

                    b.HasIndex("SolicitacaoProdutoSolicitacaoid", "SolicitacaoProdutoProdutoid");

                    b.ToTable("itensCotacao");
                });

            modelBuilder.Entity("SistemaCompra.Domain.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<double>("PrecoUnit")
                        .HasColumnType("double");

                    b.Property<int>("QtdeProduto")
                        .HasColumnType("int");

                    b.Property<int>("itemCotacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("itensPedido");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aprovador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAprovacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StatusAprov")
                        .HasColumnType("int");

                    b.Property<int>("cotacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FamiliaProdId")
                        .HasColumnType("int");

                    b.Property<int?>("FamiliaProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("UnidMedida")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aprovador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CotacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAprovacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNecessidade")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StatusAprovacao")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Solcitacoes");
                });

            modelBuilder.Entity("SistemaCompra.Domain.SolicitacaoProduto", b =>
                {
                    b.Property<int>("Solicitacaoid")
                        .HasColumnType("int");

                    b.Property<int>("Produtoid")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("QtdeProduto")
                        .HasColumnType("int");

                    b.HasKey("Solicitacaoid", "Produtoid");

                    b.HasIndex("Produtoid");

                    b.ToTable("solicitacaoProduto");
                });

            modelBuilder.Entity("SistemaCompra.Domain.user", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Setor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Cotacao", b =>
                {
                    b.HasOne("SistemaCompra.Domain.Pedido", "Pedido")
                        .WithOne("cotacao")
                        .HasForeignKey("SistemaCompra.Domain.Cotacao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCompra.Domain.Solicitacao", "Solicitacao")
                        .WithOne("Cotacao")
                        .HasForeignKey("SistemaCompra.Domain.Cotacao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCompra.Domain.Fornecedor", "fornecedorid")
                        .WithMany("Cotacoes")
                        .HasForeignKey("fornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fornecedorid");

                    b.Navigation("Pedido");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Fornecedor", b =>
                {
                    b.HasOne("SistemaCompra.Domain.FamiliaProduto", "FamiliaProduto")
                        .WithMany("Fornecedores")
                        .HasForeignKey("FamiliaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FamiliaProduto");
                });

            modelBuilder.Entity("SistemaCompra.Domain.ItemCotacao", b =>
                {
                    b.HasOne("SistemaCompra.Domain.Cotacao", "Cotacao")
                        .WithMany("ItensCotacao")
                        .HasForeignKey("cotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCompra.Domain.SolicitacaoProduto", "SolicitacaoProduto")
                        .WithMany()
                        .HasForeignKey("SolicitacaoProdutoSolicitacaoid", "SolicitacaoProdutoProdutoid");

                    b.Navigation("Cotacao");

                    b.Navigation("SolicitacaoProduto");
                });

            modelBuilder.Entity("SistemaCompra.Domain.ItemPedido", b =>
                {
                    b.HasOne("SistemaCompra.Domain.ItemCotacao", "itemCotacao")
                        .WithOne("itemPedido")
                        .HasForeignKey("SistemaCompra.Domain.ItemPedido", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCompra.Domain.Pedido", "Pedido")
                        .WithMany("itensPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("itemCotacao");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Produto", b =>
                {
                    b.HasOne("SistemaCompra.Domain.FamiliaProduto", "FamiliaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("FamiliaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FamiliaProduto");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Solicitacao", b =>
                {
                    b.HasOne("SistemaCompra.Domain.user", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaCompra.Domain.SolicitacaoProduto", b =>
                {
                    b.HasOne("SistemaCompra.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("Produtoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCompra.Domain.Solicitacao", "Solicitacao")
                        .WithMany("SolicitaoProdutos")
                        .HasForeignKey("Solicitacaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Cotacao", b =>
                {
                    b.Navigation("ItensCotacao");
                });

            modelBuilder.Entity("SistemaCompra.Domain.FamiliaProduto", b =>
                {
                    b.Navigation("Fornecedores");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Fornecedor", b =>
                {
                    b.Navigation("Cotacoes");
                });

            modelBuilder.Entity("SistemaCompra.Domain.ItemCotacao", b =>
                {
                    b.Navigation("itemPedido");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Pedido", b =>
                {
                    b.Navigation("cotacao");

                    b.Navigation("itensPedidos");
                });

            modelBuilder.Entity("SistemaCompra.Domain.Solicitacao", b =>
                {
                    b.Navigation("Cotacao");

                    b.Navigation("SolicitaoProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
